/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControl } from "./AccessControl";
export type { IAccessControl } from "./IAccessControl";
export type { ERC20 } from "./ERC20";
export type { ERC20Burnable } from "./ERC20Burnable";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20 } from "./IERC20";
export type { ERC721 } from "./ERC721";
export type { ERC721Burnable } from "./ERC721Burnable";
export type { IERC721Metadata } from "./IERC721Metadata";
export type { IERC721 } from "./IERC721";
export type { IERC721Receiver } from "./IERC721Receiver";
export type { ERC165 } from "./ERC165";
export type { IERC165 } from "./IERC165";
export type { Arcades } from "./Arcades";
export type { ScrapToken } from "./ScrapToken";

export { AccessControl__factory } from "./factories/AccessControl__factory";
export { IAccessControl__factory } from "./factories/IAccessControl__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { ERC20Burnable__factory } from "./factories/ERC20Burnable__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { ERC721__factory } from "./factories/ERC721__factory";
export { ERC721Burnable__factory } from "./factories/ERC721Burnable__factory";
export { IERC721Metadata__factory } from "./factories/IERC721Metadata__factory";
export { IERC721__factory } from "./factories/IERC721__factory";
export { IERC721Receiver__factory } from "./factories/IERC721Receiver__factory";
export { ERC165__factory } from "./factories/ERC165__factory";
export { IERC165__factory } from "./factories/IERC165__factory";
export { Arcades__factory } from "./factories/Arcades__factory";
export { ScrapToken__factory } from "./factories/ScrapToken__factory";
